# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mguillot <mguillot@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/09/02 13:43:40 by mguillot          #+#    #+#              #
#    Updated: 2024/11/04 19:18:30 by mguillot         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc -Wall -Wextra -Werror -o ft_display_file ft_main.c

clean:
	rm -rf *.o

fclean: clean
	rm -rf ft_display_file
